version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Full.Dockerfile
    container_name: digital-wallet-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/sites-available/default
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=digital_wallet
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
      - CACHE_DRIVER=database
      - SESSION_DRIVER=database
      - QUEUE_CONNECTION=database
    networks:
      - digital-wallet-network

  mysql:
    image: mysql:8.0
    container_name: digital-wallet-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digital_wallet
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - digital-wallet-network

volumes:
  mysql_data:
    driver: local

networks:
  digital-wallet-network:
    driver: bridge
